import bcryt from "bcryptjs";

const data = {
  users: [
    {
      name: "admin",
      email: "admin@gmail.com",
      password: bcryt.hashSync("12345"),
      mobile: 8830711743,
      isAdmin: true,
    },
    {
      name: "user1",
      email: "user1@gmail.com",
      password: bcryt.hashSync("12345"),
      isAdmin: false,
      mobile: 9881272631,
    },
  ],
  products: [

    {
      name: `Mesmerising Intricate Bangle`,
      slug: `mesmerising-intricate-bangle`,
      collections: "Gold",
      category: "Bangle",
      image: "/assets/images/b-01.jpg",
      price: 35000,
      countInStock: 15,
      rating: 4,
      numReviews: 20,
      description: `Dip in decadence when you adorn this mesmerising intricate bangle crafted in 22 karat yellow gold`,
    },
    {
      name: `Chic Geometric Diamond Bangle`,
      slug: `chic-geometric-diamond-bangle`,
      collections: "Diamond",
      category: "Bangle",
      image: "/assets/images/b-02.jpg",
      price: 23700,
      countInStock: 15,
      rating: 4,
      numReviews: 20,
      description: `Classy geometric design forms this dazzling bangle crafted in 18 karat yellow gold studded with diamonds. Stone Clarity: SI2 G-H`,
    },
    {
      name: `Pink Champagne Diamond Bracelet`,
      slug: `pink-champagne-diamond-bracelet`,
      collections: "Diamond",
      category: "Bracelet",
      image: "/assets/images/br-01.jpg",
      price: 21047,
      countInStock: 15,
      rating: 4,
      numReviews: 20,
      description: `Let the celebration of your love begin with this enticing bracelet, crafted beautifully with pink colour stone and dazzling diamonds!`,
    },
    {
      name: `Girl's Bows Bracelet`,
      slug: `girls-bows-bracelet`,
      collections: "Gold",
      category: "Bracelet",
      image: "/assets/images/p-01.jpg",
      price: 51663,
      countInStock: 5,
      rating: 4.5,
      numReviews: 5,
      description: `Diamond studded round frame with girl's bow and ribbons, girl's diamond bracelet with bows & ribbons - few phrases that aptly describe this jewellery. This Bracelet is made of 5.53 grams of BIS hallmarked gold & comes with our lifetime exchange guarantee. It is studded with 19 diamonds, weighing 0.1481 carats in total (1 carat = 100 cents). Needless to say, all diamond & gemstone studded bracelet from KuberBox are certified by reputed diamond labs. The authenticity certificate will be sent with the order by default. Chain length customization is/are available. Kindly select the relevant option before adding the product to your cart. You may speak to our jewellery experts for more clarity and help with customization.`,
    },
    {
      name: `Enticing Twisted Chain`,
      slug: `enticing-twisted-chain`,
      collections: "Gold",
      category: "Chain",
      image: "/assets/images/c-01.jpg",
      price: 18825,
      countInStock: 3,
      rating: 4.5,
      numReviews: 15,
      description: `Look stunning when you adorn this enticing chain, with twisted ropes pattern, crafted in 22 karat yellow gold`,
    },
    {
      name: `Sleek Foxtail Diamond Chain`,
      slug: `sleek-foxtail-diamond-chain`,
      collections: "Diamond",
      category: "Chain",
      image: "/assets/images/c-02.jpg",
      price: 9500,
      countInStock: 3,
      rating: 4.5,
      numReviews: 15,
      description: `Sleek foxtail chain set in 18 karat yellow gold. Stone quality - VVS. The sleek design makes this a perfectly versatile jewellery.`,
    },
    {
      name: `Exquisite Filigree Earrings`,
      slug: `exquisite-filigree-earrings`,
      collections: "Gold",
      category: "Earings",
      image: "/assets/images/p-03.jpg",
      price: 19345,
      countInStock: 3,
      rating: 4.5,
      numReviews: 15,
      description: `Filigree is the new trend and new and trendy is what we do! This exquisite pair of earrings has a filigree pattern which is intricate and neat. Through this runs lines of Diamonds looking awesome. Boost your glam quotient by donning this lovely pair. Customize this jewelry with gold purity, diamond quality and gold colour of your choice.`,
    },
    {
      name: `Abstract Floral Stud Earrings`,
      slug: `abstract-floral-stud-earrings`,
      collections: "Diamond",
      category: "Earing",
      image: "/assets/images/e-01.jpg",
      price: 22500,
      countInStock: 15,
      rating: 4,
      numReviews: 20,
      description: `A fusion of abstracts and florals, these stud earrings are crafted in 22 karat yellow gold`,
    },
    {
      name: `Charming Paisley Mangalsutra`,
      slug: `charming-paisley-mangalsutra`,
      collections: "Diamond",
      category: "Mangalsutra",
      image: "/assets/images/m-01.jpg",
      price: 14500,
      countInStock: 10,
      rating: 4.5,
      numReviews: 20,
      description: `Keep your style charming and sophisticated with this mangalsutra crafted in 18 karat yellow gold, studded with diamonds. Stone Clarity: I1/I2.`,
    },
    {
        name: `Delightful Loop Mangalsutra`,
        slug: `delightful-loop-mangalsutra`,
        collections: "Gold",
        category: "Mangalsutra",
        image: "/assets/images/m-02.jpg",
        price: 16500,
        countInStock: 15,
        rating: 4,
        numReviews: 20,
        description: `Be a delightful presence with this modern style loop pattern mangalsutra crafted in 22 karat yellow gold`,
      },
      {
        name: `Twinkling Spiral Diamond, Sapphire and Ruby Necklace Set`,
        slug: `twinkling-spiral-diamond, sapphire-and-ruby-necklace-set`,
        collections: "Diamond",
        category: "Necklace",
        image: "/assets/images/n-01.jpg",
        price: 25000,
        countInStock: 8,
        rating: 4.5,
        numReviews: 20,
        description: `Set in a modern silhouette, this necklace set has a lovely gradation from sapphires and rubies to diamonds, crafted in 18 karat yellow and white gold`,
      },
      {
        name: `Glamorous Traditional Gold Sita Haar Necklace`,
        slug: `glamorous-traditional-gold-sita-haar-necklace`,
        collections: "Gold",
        category: "Necklace",
        image: "/assets/images/n-02.jpg",
        price: 35000,
        countInStock: 10,
        rating: 4,
        numReviews: 20,
        description: `Make an unforgettable style statement with this enticing Sita Haar for all Indian Brides crafted in 22 karat yellow gold`,
      },
      {
        name: `Studded Heart Pendant`,
        slug: `studded-heart-pendant`,
        collections: "Gold",
        category: "Pendent",
        image: "/assets/images/p-04.jpg",
        price: 14036,
        countInStock: 12,
        rating: 4,
        numReviews: 20,
        description: `Small & petite. The beautiful small heart shaped gold figures intertwined each other. One studded, while one plain gold. Pair them with matching earrings for best effect. Go ahead & customize it with options in Gold Purity (18K, 14K), Diamond Grade (SI-HI, VS-GH, VVS-GH) & Metal Colour (Yellow, White, Rose) of your liking. Create your own unique jewelry.`,
      },
      {
        name: `Elegant 18 Karat Yellow Gold And Diamond Leaf Pendant`,
        slug: `elegant-18-karat-yellow-gold-and-diamond-leaf-pendant`,
        collections: "Diamond",
        category: "Pendent",
        image: "/assets/images/pe-01.jpg",
        price: 20040,
        countInStock: 10,
        rating: 4,
        numReviews: 20,
        description: `This lovely 18 Karat yellow gold pendant features a slender stalk of gold with 1 diamond-studded leaf and a bud, on either side. Stone Clarity: SI2`,
      },
      {
        name: `Timeless Leafy Ring`,
        slug: `timeless-leafy-ring`,
        collections: "Gold",
        category: "Rings",
        image: "/assets/images/r-01.jpg",
        price: 19526,
        countInStock: 15,
        rating: 4,
        numReviews: 20,
        description: `Add the timeless wonder of nature in your everyday style with this ring, crafted in 22 karat yellow gold`,
      },
      {
        name: `Tickle Pink Diamond Ring`,
        slug: `tickle-pink-diamond-ring`,
        collections: "Diamond",
        category: "Rings",
        image: "/assets/images/r-02.jpg",
        price: 12426,
        countInStock: 0,
        rating: 5,
        numReviews: 10,
        description: `Be a presence of joy and amusement when you adorn the brilliance of this charming ring, with glinting diamonds and pink colour stone!`,
      },
      
  ],
};

export default data;